name: shop_app_clean_architecture
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # for bloc state management
  flutter_bloc: ^8.1.3
  # for dependency injection
  get_it: ^7.6.0
  # http
  http: ^0.13.6
  # to check internet connectivity
  internet_connection_checker: ^1.0.0+1
  # to store some data localy
  shared_preferences: ^2.1.2
  cupertino_icons: ^1.0.2
  # brings functional programming features to dart
  dartz: ^0.10.1
  # to help compare class more easely
  equatable: ^2.0.5
  # provider state management package
  provider: ^6.0.5
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
